[package]
name    = "openal-sys"
version = "1.16.0-3"

authors = ["meh. <meh@schizofreni.co>"]
license = "WTFPL"

description = "FFI bindings to OpenAL"
repository  = "https://github.com/meh/rust-openal-sys"
keywords    = ["audio"]

[dependencies]
libc = "*"
